version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: student_management_user
      POSTGRES_USER: prog
      POSTGRES_PASSWORD: Leander7
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data

  discovery-service:
    build:
      context: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - backend

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - discovery-service
    networks:
      - backend

  course-service:
    build:
      context: ./course-service
    container_name: course-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - discovery-service
    networks:
      - backend

  enrollment-service:
    build:
      context: ./enrollment-service
    container_name: enrollment-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - discovery-service
    networks:
      - backend

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    depends_on:
      - rabbitmq
    ports:
      - "8084:8084"
    networks:
      - backend

  frontend:
    build:
      context: ../student-course-frontend
    container_name: student-course-frontend
    ports:
      - "4200:80"
    depends_on:
      - api-gateway
    networks:
      - backend

networks:
  backend:

volumes:
  pgdata:

